import { useEffect, useState } from "react";
import type { FormEvent, ReactNode } from "react";

import { ApiError, api } from "../lib/api";

export function AuthGate({ children }: { children: ReactNode }) {
  const [authenticated, setAuthenticated] = useState(false);
  const [checking, setChecking] = useState(Boolean(api.getOperatorToken()));
  const [token, setToken] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!api.getOperatorToken()) return;
    let active = true;
    void api.verifyOperatorToken()
      .then(() => {
        if (active) setAuthenticated(true);
      })
      .catch(() => {
        api.clearOperatorToken();
      })
      .finally(() => {
        if (active) setChecking(false);
      });
    return () => {
      active = false;
    };
  }, []);

  const login = async (event: FormEvent) => {
    event.preventDefault();
    const value = token.trim();
    if (!value) return;

    setBusy(true);
    setError(null);
    api.setOperatorToken(value);
    try {
      await api.verifyOperatorToken();
      setToken("");
      setAuthenticated(true);
    } catch (caught) {
      api.clearOperatorToken();
      if (caught instanceof ApiError && caught.status === 401) {
        setError("Invalid operator token.");
      } else {
        setError(caught instanceof Error ? caught.message : "Unable to reach Nidavelir Core.");
      }
    } finally {
      setBusy(false);
    }
  };

  const logout = () => {
    api.clearOperatorToken();
    setAuthenticated(false);
    setToken("");
  };

  if (checking) {
    return <main className="auth-shell"><span className="muted">Checking operator session…</span></main>;
  }

  if (!authenticated) {
    return (
      <main className="auth-shell">
        <form className="auth-card" onSubmit={login}>
          <span className="eyebrow">Operator access</span>
          <h1>Nidavelir</h1>
          <p>Enter the operator token generated by the self-host installer.</p>
          <label>
            Operator token
            <input
              autoComplete="current-password"
              autoFocus
              type="password"
              value={token}
              onChange={(event) => setToken(event.target.value)}
            />
          </label>
          {error && <span className="form-error">{error}</span>}
          <button className="button" disabled={busy || !token.trim()} type="submit">
            {busy ? "Checking…" : "Unlock control plane"}
          </button>
          <small>Stored only in this browser session.</small>
        </form>
      </main>
    );
  }

  return (
    <>
      <button className="operator-logout" type="button" onClick={logout}>
        Lock
      </button>
      {children}
    </>
  );
}
